### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Zamrod** [p4535992/foundryvtt-automated-polymorpher#25]
**Module Version:** v1.1.9
**System Verison:** v2.0.3
**Foundry Version:** v10.286

**Describe the bug**
After using the button to polymorph into an Aboleth from the SRD, when you open the character sheet afterwards you get errors in the console:

```
automated-polymorpher | Acolyte turns into a Aboleth
commons.js:6916 Foundry VTT | Created Actor with id [pvw0S5UpniLzTBJf]
lib.js:73 automated-polymorpher | A - test mutate into a Aboleth
foundry.js:5058 Foundry VTT | Rendering ActorSheet5eNPC

Uncaught (in promise) Error: Item is not a valid embedded Document within the Token Document
[Detected 1 package: system:dnd5e]
    at TokenDocument5e.getEmbeddedCollection (commons.js:6260:15)
    at TokenDocument5e.getEmbeddedCollection (foundry.js:21972:39)
    at TokenDocument5e.getEmbeddedDocument (commons.js:6276:31)
    at _resolveEmbedded (foundry.js:4170:15)
    at fromUuid (foundry.js:4083:32)
    at ActiveEffect5e._getSourceName (foundry.js:16043:26)
    at ActiveEffect5e.prepareActiveEffectCategories (active-effect.mjs:133:9)
    at ActorSheet5eNPC.getData (base-sheet.mjs:96:31)
    at ActorSheet5eNPC.getData (npc-sheet.mjs:27:33)
    at ActorSheet5eNPC._render (foundry.js:5067:29)
    at ActorSheet5eNPC._render (foundry.js:5780:17)
    at ActorSheet5eNPC.render (foundry.js:5026:10)
    at ActorSheet5eNPC.render (foundry.js:6352:18)
    at Token5e._onClickLeft2 (foundry.js:46736:16)
    at MouseInteractionManager.callback (foundry.js:26367:45)
    at MouseInteractionManager._handleClickLeft2 (foundry.js:26581:17)
    at MouseInteractionManager._handleMouseDown (foundry.js:26543:66)
    at a.emit (index.js:181:35)
    at r.dispatchEvent (interaction.min.mjs:8:12235)
    at r.processPointerDown (interaction.min.mjs:8:14214)
    at t.recursiveFindHit (interaction.min.mjs:8:4098)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.findHit (interaction.min.mjs:8:4157)
    at r.processInteractive (interaction.min.mjs:8:12841)
    at r.onPointerDown (interaction.min.mjs:8:13543)
```

This does not happen when using the built in Polymorpher without the module.

**To Reproduce**
1. Go to a token
2. Click on Polymorpher icon
3. Click on Aboleth
4. Open character sheet
5. See error

**Comment by p4535992** [comment]
Cannot replicate,  must be some active effect or item on the source actor can you export the json actor data ? (rename the file with ".txt" for github limitation.

**Comment by p4535992** [comment]
Sorry, but between limited free time and the fact that I am not exceptional with code I am forced to abandon the module I have opened a ticket for anyone interested to coordinate to rewrite a new one https://discord.com/channels/732325252788387980/1076817951623229500
