### ISSUE TITLE
Polymorph not working

### ISSUE THREAD

**Issue by BigJohno5001** [p4535992/foundryvtt-automated-polymorpher#26]
Not sure where else to put this but, im really not sure why this is happening. I had it working for one session then it broke, and now i just cant get it to work again. 

![ezgif-2-22c748c736](https://user-images.githubusercontent.com/43619421/195929000-b123dff1-6d77-4011-a4ba-0619ca318483.gif)

**Comment by p4535992** [comment]
@BigJohno5001 sorry i cannot read the text on the yellow message, can you copy and paste the text here ?

**Comment by BigJohno5001** [comment]
@p4535992 Yes no worries, i didnt realise how low res it was.

**automated-polymorpher | The actor you are trying to polimorphing not exists anymore, please set up again the actor on the polymorpher manager**

however now when i goto do it, i dont get any error pop up but still nothing happens
I have these errors in my console though

**lib.js:388 Sequencer | Effect | belowTokens - This method has been deprecated due to fundamental changes in Foundry's V10 update, please use .elevation() instead.
custom_warning @ lib.js:388
lib.js:73 automated-polymorpher | Iris Phantom turns into a Commoner
dnd5e.js:1228 Uncaught (in promise) TypeError: effect.toObject is not a function
[Detected 1 package: automated-polymorpher]
    at Object.prepareDataFromTransformOptions (dnd5e.js:1228:38)
    at Object.transformInto (dnd5e.js:115:30)
    at async Object.callback (dnd5e.js:728:25)**

**Comment by p4535992** [comment]
Can you export the commoner actor json data ? and tell me what browser are you using ?

**Comment by p4535992** [comment]
Add some more check 1.1.12, but wihtout the actor with the issue to test i'm not sure if i solved the problem.

**Comment by p4535992** [comment]
i add some more check not sure about the resolution .without  check the data on the actors witth he problem

**Comment by p4535992** [comment]
@BigJohno5001  Works fine for me on my dnd5e  worlds, at this point or is it the source actor (please pass to me that) or the browser used, are you using chrome?

**Comment by BigJohno5001** [comment]
[fvtt-Actor-iris-phantom.txt](https://github.com/p4535992/foundryvtt-automated-polymorpher/files/9799432/fvtt-Actor-iris-phantom.txt)

Hi ive attached the actor, im using the foundry.exe

**Comment by yarvito** [comment]
Having similar problem, in my case the console error:

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'type')
[Detected 1 package: automated-polymorpher]
    at dnd5e.js:1189:28
    at Array.filter (<anonymous>)
    at Object.prepareDataFromTransformOptions (dnd5e.js:1174:35)
    at Object.transformInto (dnd5e.js:119:30)
    at async Object.callback (dnd5e.js:773:25)

**Comment by yarvito** [comment]
ok I updated to latest version anc clean install the module and now works.

**Comment by p4535992** [comment]
yes but there is still something i need to correct

**Comment by Kharrie** [comment]
Hi, im having the exact same problem, the animation goes off but the token doesnt change to the shape shifter one... not sure how did this guy solve it, i uninstalled the mod and install it again but no success, i dont know how to make a clean installation without touching my wolrd or any other module. thanks

**Comment by Kharrie** [comment]
ok so apparently the actor i started trying broke, and i was able to get a transformation at all with him, but im trying with another actors and it works fine... i have no idea what is wrong but if you want information from my console so you can work on it just let me know. have a good day

**Comment by p4535992** [comment]
Sorry, but between limited free time and the fact that I am not exceptional with code I am forced to abandon the module I have opened a ticket for anyone interested to coordinate to rewrite a new one https://discord.com/channels/732325252788387980/1076817951623229500
