### ISSUE TITLE
[BUG] Broken in 2.1.1 & 2.1.2

### ISSUE THREAD

**Issue by plumppig** [p4535992/foundryvtt-automated-polymorpher#31]
**Module Version:**
v1.1.13

**Describe the bug**
When you attempt to polymorph using this module, it performs the magical effect correctly but will throw an error before transforming the token.

**To Reproduce**
1. Right click a token
2. Click the polymorpher icon
3. Click the transform icon of any creature in the list
4. Observe the error

**Expected behavior**
I expect to see a magical effect preceding the transformation of the token into the desired creature.

**Screenshots**
![Screenshot 2023-01-13 at 10 37 25 PM](https://user-images.githubusercontent.com/5460707/212457694-39e6821e-c9b5-4476-b9e3-d5909d4460ca.png)

**Browser:**
 - Chrome

**Foundry Version:** 
Version 10 (291)

**Game System:** 
DnD 5e v2.1.2

**Additional context**
[broken_polymorpher.log](https://github.com/p4535992/foundryvtt-automated-polymorpher/files/10416742/broken_polymorpher.log)

**Comment by arcanjl** [comment]
I was just coming here with this issue :(

**Comment by martinnyborg** [comment]
Yep seeing the exact same thing here

**Comment by Shadowzlair** [comment]
Seeing the exact same error, any news on a solution? Looking forward in using this in my group sessions

**Comment by dyoung522** [comment]
Not sure if it's the same bug, but I'm getting this error with the same behavior described above (animations play but actor does not change)

```js
dnd5e.js:1222 Uncaught (in promise) TypeError: undefined. effect.toJSON is not a function
[Detected 1 package: automated-polymorpher]
    at Object.prepareDataFromTransformOptions (dnd5e.js:1222:36)
    at Object.transformInto (dnd5e.js:119:30)
    at async Object.transformIntoImpl (api.js:362:20)
    at async Object.transformIntoArr (api.js:286:27)
    at async Object.transformInto (api.js:290:27)
    at async PolymorpherManager.fastSummonPolymorpher (polymorphermanager.js:608:13)
```

This is in module version 1.1.14

**Comment by p4535992** [comment]
Sorry, but between limited free time and the fact that I am not exceptional with code I am forced to abandon the module I have opened a ticket for anyone interested to coordinate to rewrite a new one https://discord.com/channels/732325252788387980/1076817951623229500

**Comment by arcanjl** [comment]
I wish I could ☺️

Sent from my iPhone

On Feb 22, 2023, at 3:27 PM, 4535992 ***@***.***> wrote:

﻿

Sorry, but between limited free time and the fact that I am not exceptional with code I am forced to abandon the module I have opened a ticket for anyone interested to coordinate to rewrite a new one https://discord.com/channels/732325252788387980/1076817951623229500

**Comment by dyoung522** [comment]
I may be able to help, but that discord link doesn't work for me.

**Comment by p4535992** [comment]
A maybe you must enter on the discord server here the invite: https://discord.gg/rNzh6U2qMG
